### PR TITLE
Fix issues for AMO

### PR DESCRIPTION
**Pull request by publicarray**
Is the web-extention on AMO? I can't find it. If not would it be OK if I (or someone else) published it on AMO? or maintained a fork? thanks for the extension btw.

@meh would you be willing to add a licence file to the repository?

### CODE REVIEW

**Comment by publicarray** [comment]
cc @alexander255

**Comment by alexander255** [comment]
Ideally we can get a clean upgrade path for the current add-on so that things just "continue to work", without anybody noticing the plenty of changes that went into the new version. So please don't publish anything yet! It really depends on whether we get @meh's blessings of not, through…

Anyway I've cherry-picked your *fix bugs*-commit into #48 (yes, you'll get attribution for that commit). I was wondering what the other commit does through?

**Comment by publicarray** [comment]
Ok agreed, I'm just worried that @meh is no longer interested in the extension and won't reply. The last commit was because the checkboxes didn't show on my Fire Fox nightly. I haven't tested if it was a specific to my setup or if it was a bug in nightly or whatever but setting the CSS to `display:block` fixed the issue.

**Comment by meh** [comment]
Yeah, I'm really sorry, I've been really busy lately and haven't had time to review the changes yet, I'll try to review and merge #48 today.

**Comment by alexander255** [comment]
@meh: Yes, please review but don't quite merge yet I have a couple patches in the pipeline right now that will probably need lots of testing

@publicarray: Why did you add the ´"http://*/*"` and `"https://*/*"` permissions? Are they actually needed on Nightly?

**Comment by publicarray** [comment]
> Are they actually needed on Nightly?

Yes, though I don't know at which version it became a requirement.

**Pull request closed without merging**
