### PR TITLE
Added link to non-minimized whitelist

### PR DESCRIPTION
**Pull request by Gitoffthelawn**
This way people can see the important comments and understand the entries more effectively.

### CODE REVIEW

**Comment by Gitoffthelawn** [comment]
See also https://github.com/meh/smart-referer/issues/55

**Comment by alexander255** [comment]
Wouldn't it be better to include this information as a comment within the minimized whitelist file itself? I actually planned on doing this instead when you made the comment. The whitelist file probably has more exposure than the README, I'd think.

**Comment by Gitoffthelawn** [comment]
Does the whitelist need to be minimized?

**Comment by alexander255** [comment]
Originally yes, when I took over the whitelist *Smart Referer* wouldn't understand any comments. Nowadays (at least post-0.2, probably earlier) it does support comments so we don't need it for that anymore. However the minification also current results in a 59,3% compression, which means the file is only 565, instead of 1389 bytes large… :trollface: 

In other words: Yes, we *can* probably drop the minimizer altogether…

**Comment by Gitoffthelawn** [comment]
@alexander255 I haven't had a chance to look... is the minimizer code in the extension or in an external prep routine outside of the extension?

**Comment by alexander255** [comment]
It's an extra script: https://github.com/meh/smart-referer/blob/gh-pages/build.awk
(I should have written it in `sed` instead of `awk` to make it's contents unreadable through, 😁)

**Comment by Gitoffthelawn** [comment]
I'm fine leaving it minimized, now that the full version is easy to find.  A byte is a byte is a byte...

**Comment by alexander255** [comment]
I've added a link in the minimized whitelist file, so that people can quickly find the non-minimized version. I also dropped so many dead entries from the whitelist that minimizing it really isn't worth it anymore.

I seems that web browser have done such a good job [making this header](https://stackoverflow.com/questions/1390862/http-referer-lost-using-https) [quite unreliable](https://stackoverflow.com/questions/6880659/in-what-cases-will-http-referer-be-empty) that web authors simply don't trust it anymore. 🤗 (@browser-vendors: Awesome job on this one!)

**Pull request closed without merging**
