### PR TITLE
Add WebExtension port of this add-on

### PR DESCRIPTION
**Pull request by alexander255**
Most stuff was rewritten and (if possible) simplified, the only truely original piece of code is the policy engine that processes the whitelist entries.

Also contains a newly "designed" logo that is used for the toolbar icon requested #27.

Except for not preserving the previous settings this add-on does everything the previous iteration of *Smart Referer* did and more!

### CODE REVIEW

**Comment by alexander255** [comment]
For a discussion about how settings migration might work see #47.

**Comment by meh** [comment]
Just a note I'm not ignoring all of this, it's just I'm on vacation 🐼

**Comment by alexander255** [comment]
So here is the final version of this (for now):
screenshot_20170109_215630

As you can see I've added a more user-friendly UI for managing exceptions. Additionally smart referer can now be enabled and disabled using the checkbox in the options OR using the icon on the toolbar. Everything else is unchanged (aside from be implemented as a WebExtension).

@meh Thanks for your feedback on your current “status”. Have a nice holiday! 🙂

**Comment by alexander255** [comment]
I don't want to be annoying or anything but have you had time to take a look at this by now, @meh? In particular, since Firefox 51 has now been released, it'd be possible to release an intermediate version of this add-on that migrates the settings from the old (non-WebExtension) version of this add-on to the newly written code-base.
Do you think that would be worth the hassle to look into?

**Comment by alexander255** [comment]
Since somebody (@publicarray) asked about this, I think I will complete what I've started here.
Since Firefox 51 has already been out for some weeks, we can now use embedded WebExtensions to also do a proper preferences migration. Users should then be able to upgrade to this version **without any loss of data**.

@meh: Would you review and let me publish this upgrade on AMO?

**Comment by alexander255** [comment]
OK, I think I'm done for now; awaiting any review and particularly **some testing**.

**"Building" the code**: Just run `make xpi` and use the result.

**How to test the migration (please don't just "throw it in there", I need real feedback if things go wrong!)**:

  - You will need at least Firefox 51 or newer (the WebExtension itself is compatible with Firefox 45+, but the shim requires a newer version…)
  - Make a backup of the `user.js` file of your current Firefox profile (you'll need it if the migration fails)
  - Close the browser and **launch it from terminal**
  - Open the Browser-Console using `Ctrl`+`Shift`+`J`
  - Install the new version of the extension in the browser (you may need to disable `xpinstall.signatures.required` in `about:config` for this to work)
    - You should see messages from *SmartReferer.LegacyPrefs* in the terminal and stuff about a "preference migration" in the Browser-Console window
  - Open the add-on list (`about:addons`) and verify that all preferences have been properly migrated
  - Open the browser configuration (`about:config`) and verify that all `smart-referer` related preferences are gone
  - Use the network logs in the Browser-Console to verify that the `Referer` values are indeed updated as expected while browsing

If errors happen during the migration I will need both the relevant terminal and Browser-Console output!

**Comment by publicarray** [comment]
I tested the migration from a clean Ff profile. It works as expected however I did not follow your instructions as `make xpi` errored on my mac: 

```
zip error: Nothing to do! (smart-referer.xpi)
make: *** [smart-referer.xpi] Error 12
```

**Comment by alexander255** [comment]
@publicarray: Thanks for your feedback!

*Regarding the `make xpi` error*:
Do have GIT installed and in your path on that device? It does actually require that to obtain the file list.
If you do, could you run this in your terminal and paste the result: `git ls-files | grep -v '^[.]' | grep -vx 'Makefile' | grep -v '^webextension/deps/public-suffix-list'`
Thanks!

@meh: What's your timeframe on providing initial feedback on this?

**Comment by publicarray** [comment]
@alexander255 will do, here is the output:
```
~ ❯ cd git/smart-referer
~/g/smart-referer meh/wext ❯ git --version
git version 2.12.2
hub version 2.2.9
~/g/smart-referer meh/wext ❯ git ls-files | grep -v '^[.]' | grep -vx 'Makefile' | grep -v '^webextension/deps/public-suffix-list'
README.md
bootstrap.js
install.rdf
options.xul
webextension/deps/wext-options/options.css
webextension/deps/wext-options/options.js
webextension/gecko45-shim.js
webextension/icon-light.svg
webextension/icon.js
webextension/icon.svg
webextension/main.js
webextension/manifest.json
webextension/options.html
webextension/options.js
webextension/policy.js
~/g/smart-referer meh/wext ❯ make xpi

zip error: Nothing to do! (smart-referer.xpi)
make: *** [smart-referer.xpi] Error 12
```

I tired gnu's make (`brew install make`) and it works:
```
~/g/smart-referer meh/wext ❯ gmake xpi
  adding: README.md (deflated 55%)
  adding: bootstrap.js (deflated 67%)
         ...
  adding: webextension/policy.js (deflated 53%)
  adding: webextension/deps/public-suffix-list/dist/psl.js (deflated 69%)
~/g/smart-referer meh/wext ❯ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
~/g/smart-referer meh/wext ❯ gmake --version
GNU Make 4.2.1
Built for x86_64-apple-darwin15.5.0
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by alexander255** [comment]
publicarray: That version of GNU Make is ancient and doesn't support the `.ONESHELL` feature (introduced in version 3.82). Apparently Apple stopped updating their GNU components after they switched to GPLv3+ because they don't like the FSF or patent grants or who-knows-what.
Don't you think it's "worth it" to work around Apple?

**Comment by alexander255** [comment]
@publicarray: Fixed the build so that it should work with macOS as well. Please give feedback on this!

**Comment by meh** [comment]
@alexander255 looks good to me.

**Comment by alexander255** [comment]
@meh: So you're okay with merging it as-is? No further comments, etc?

**Comment by meh** [comment]
@alexander255 maybe just removing all those debugging `dump`s, otherwise I'm fine with it.

**Comment by publicarray** [comment]
@alexander255  All good on the makefile :)  Works with both versions now.

**Comment by alexander255** [comment]
Thanks for testing @publicarray!

@meh: I'll do that once we have some more confirmations that this works

**Comment by alexander255** [comment]
@markraffalo1 @Nutomic @ipatjolvur @ReporterX @smith330 @SMed79 @mcbarky @neckcen @lainverse @pedrompcaetano @melodiem @Gitoffthelawn @Forsaked @klonamy @scribblemaniac

Hi everybody! 🙋‍ 

As you may have noticed *Smart Referer* is getting a rewrite in preparation of switching to the new WebExtension API that is now offered by Mozilla browsers and may become the only way to distribute add-ons for Firefox in the future. As part of this endeavor we need your feedback! All of you have either contributed (through the issue tracker) or decided to watch this project in the past, so I'll assume you have at least some interest in its well-being and availability in the feature.
(If not then please just ignore this message.)

Here's what we need you to do:

## Get the new version

### Building from source

If you can, please build the add-on from source by running these commands (Cygwin/MSYS/BashOnWindows required on Windows):

 * `git clone -b wext --recursive "https://github.com/meh/smart-referer.git" "smart-referer"` to download the repository
 * `cd "smart-referer"` to enter the downloaded repository
 * `make xpi` to assemble the extension's files

This should create a file called *smart-referer.xpi* – don't install it yet!

List of required packages: `git`, `make`, `zip` & `coreutils`

### Prebuilt version

Please build from source if you can, we want that to work reliably as well. Otherwise you can
download a prebuilt version here (do not install it yet, just download!):

https://storage.xmine128.tk/index.php/s/kAgAzzBSdQkfwOD

## Test the migration to the new version

Please follow the guide! Don't just install the XPI! We need actual feedback if things go wrong.

 1. You will need at least Firefox 51 or newer
 2. Make a backup of the `user.js` file of your current Firefox profile directory
    (you may need it if the migration fails)
 3. Close the browser and **launch it from terminal**
 4. Open the Browser-Console using `Ctrl`+`Shift`+`J`
 5. If you have not done so previously, please disable add-on signature validation:
     * Type `about:config` into the address bar and press enter
     * Acknowledge the warning by pressing the *I will be careful*-button
     * Enter `xpinstall.signatures.required` in the search box
     * Double-click the first entry, so that its value changes to *false* instead of *true*
 7. Install the new version of the extension by dragging it from your file manager onto the browser window
    - Check that messages from *SmartReferer.LegacyPrefs* appear in the terminal window and stuff about a "preference migration" is logged in the Browser-Console window
 6. Open the add-on manager by typing `about:addons` into the address bar and clicking on the *Extensions* tab on the left-hand side of the page
 8. Click on *Settings*-button next to *Smart Referer* and verify that all preferences have been properly migrated
 9. Restart your browser
10. Verify that all previous configuration entries are gone:
    - Type `about:config` in the address bar and acknowledge the warning again
    - Check that there are no results when searching for `extensions.smart-referer`
11. Use the network logs in the Browser-Console to verify that the `Referer` values are indeed updated as expected while browsing
    - If you don't know how to do this, please at least [click on this link](https://www.whatismyreferer.com/) and verify that the result looks good

That's it thanks for your help!

## If things go wrong

If the migration fails for any reason, then please include a copy/screenshot of the following things in your response:

 * Relevant messages in the Browser-Console
 * Output in the terminal window
 * Settings of the old add-on version
 * Operating system & Browser Version
 * Anything else you think may be helpful in getting this fixed

## If things work as expected

Please leave a short message as well, so that we can get a feel for how well it works. Something like:

> Worked for me! (Firefox 51.0.2 / Windows 7 64-Bit)

Is enough in this case.

.

Thanks to everybody participating in this!

**Comment by publicarray** [comment]
@alexander255 Personally I would just :ship: it. We both tested it and it works, if there are settings that break than I don't think there is much harm in it. An annoyance yes, but nothing more. (This is an open source project not industrial grade software). Just my 2 cents.

**Comment by alexander255** [comment]
@publicarray: I want to get as much feedback as possible before doing that. Once the update's out it **will** do irreversible changes without any further notification. Any failure in that could mean breaking add-on functionality for users without any kind of warning or immediate indication that something is even wrong – a huge violation of trust in my book and something I really don't want to happen.
Hence why I'd like to have as much feedback as possible on this, before committing to it.

**Comment by Gitoffthelawn** [comment]
Thank you for your hard work.  I regret, that due to health issues, I will not be able to contribute any testing at this this time.  My apologies.

**Comment by SMed79** [comment]
**OS** : Manjaro XFCE 17.0.1 / 64-bit 

**Firefox** : 52.0.2 (64 bits)

**Installed Addons** : 
Adblock Plus 2.8.2
Element Hiding Helper pour Adblock Plus 1.3.10
Google search link fix 1.6.3
Random Agent Spoofer 0.9.5.6
Decentraleyes 1.3.7
Remove Cookies for Site 0.63.1
Self-Destructing Cookies 0.4.12
Smart Referer 0.0.11.1
Tab Counter 1.9.9.3
FlashStopper 1.4.5

**smart-referer.xpi** (v 0.2) ==> builted the from source

* >> Check that messages from SmartReferer.LegacyPrefs appear in the terminal window

```
1491533619330	addons.xpi	WARN	Add-on smart-referer@meh.paranoid.pk is missing bootstrap method uninstall
SmartReferer.LegacyPrefs: Reading strict:bool ...
SmartReferer.LegacyPrefs: Reading mode:char ...
SmartReferer.LegacyPrefs: Reading referer:char ...
SmartReferer.LegacyPrefs: Reading allow:char ...
SmartReferer.LegacyPrefs: Reading whitelist:char ...
SmartReferer.LegacyPrefs: Reading whitelist.to:char ...
SmartReferer.LegacyPrefs: Reading whitelist.from:char ...
SmartReferer.LegacyPrefs: Scrapped preference data: ({strict:false, mode:"self", referer:"", allow:"", whitelist:"http://meh.github.io/smart-referer/whitelist.txt"})
SmartReferer.LegacyPrefs: Clearing strict ...
SmartReferer.LegacyPrefs: Clearing mode ...
SmartReferer.LegacyPrefs: Clearing referer ...
SmartReferer.LegacyPrefs: Clearing allow ...
SmartReferer.LegacyPrefs: Clearing whitelist ...
SmartReferer.LegacyPrefs: Clearing whitelist.from ...
SmartReferer.LegacyPrefs: Clearing whitelist.to ...
SmartReferer.LegacyPrefs: Purged preference data
```

* >> stuff about a "preference migration" is logged in the Browser-Console window

```
1491533619330	addons.xpi	WARN	Add-on smart-referer@meh.paranoid.pk is missing bootstrap method uninstall
Warning: attempting to write 4569 bytes to preference extensions.bootstrappedAddons. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Warning: attempting to write 4838 bytes to preference extensions.bootstrappedAddons. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Attempting preference migration from legacy add-on…  main.js:73:3
Received preferences from legacy add-on:  main.js:75:4
Object { strict: false, mode: "self", referer: "", allow: "", whitelist: "http://meh.github.io/smart-referer/…" }  main.js:76:4
Purging preferences from legacy add-on…  main.js:96:3
Preference migration successfully completed!  main.js:102:4
```

* >> verify that all preferences have been properly migrated

smart-referer : settings

* >> Verify that all previous configuration entries are gone

smart-referer : old config

* >> verify that the Referer values are indeed updated as expected while browsing

* **Smart referer : enabled**

Smart referer : enabled

* **Smart referer : disabled**

Smart referer : disabled

* **Console** ==> `javascript:alert(document.referrer)`

Smart referer : Console check

* **Result** : ==> NO issue

**Comment by scribblemaniac** [comment]
@alexander255 I'm normally too busy for stuff like this, but since you made such a nice post on it, I decided I could at least take the time to test it. Everything appeared to work on Firefox Developer Edition 54.0a2 on macOS Sierra 64-bit (had to use the developer edition so it would allow me to install unsigned content).

**Comment by publicarray** [comment]
@alexander255 in case you don't already know. From [Mozilla's blog](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/):
> Firefox 53, April 18th release:
Unless your add-on has the multiprocessCompatible flag set to true or is a WebExtension, Firefox will run in single process mode. Firefox will run in multiprocess mode if all enabled add-ons meet this criteria.

So the current add-on on AMO will force FF to load in single process mode 😢  in about a week. I hope we can get the WebExtension on AMO before than. Keep up the good work 👍

**Comment by alexander255** [comment]
Right, so we have about 3 confirmations that things seem to work as expected. (Thanks to everybody who already participated! :+1:) Maybe we can get one or two more? :grin:

Otherwise I think we'll wrap this up by the end of the week, if that causes Firefox to run in single-process mode for a couple of days, so be it. I am planning to have this ready in time for about Firefox 53 through, so I won't delay for much longer. Please [review](https://github.com/meh/smart-referer/pull/48#issuecomment-292157689) if you can!

**Comment by alexander255** [comment]
Since nobody else commented since my last update I'm gonna merge as-is.

@meh Can you get this published on AMO? Simply running `make` on the git checkout should produce the right file to upload.

**Comment by meh** [comment]
Published, now to wait for approval. Nice work! 🐼

**Comment by alexander255** [comment]
Thanks! :grin:

**Comment by Gitoffthelawn** [comment]
What's the current AMO queue position?

**Comment by meh** [comment]
Queue Position: 228 of 278

**Comment by Gitoffthelawn** [comment]
@meh Thanks.  Wow, it's possible humans will inhabit Mars before then. ;)

**Comment by publicarray** [comment]
@meh may I ask for an update on the AMO queue position?

**Comment by meh** [comment]
@publicarray  Queue Position: 159 of 287

**Comment by publicarray** [comment]
Thanks! This looks like a race, what will come first? The FF update that disables the current add-on or the new shiny extension gets approved?

**Comment by meh** [comment]
Yeah, this is the first time it takes so long to get approved, it usually got put in front of the queue, probably because they were just minor updates.

**Comment by alexander255** [comment]
Actually the currently generated extension isn't even compatible with 57+, since it includes an unconfined migration aid -.-

The queue we're waiting in for *Smart Referer* is also **not the only one**. After submitting an update to a new (from-scratch, WExt-only, 57+) extension, it's currently number **604** of 662 (at a about 15 progress per day) in *it's* queue… Probably just about every currently maintained add-on in existence sits in that queue!
I guess guys from Mozilla are seriously drowning right now, not just are the review queues overflowing: All those missing APIs (both for feature-parity with Chrome and for allowing lots other stuff that is currently possible [toolbars, vertical tabs, accessing TLS data, managing webPage localStorage, … just to name a few]) need to be available in v55 *the latest*, so that people have at least the remaining 3 months for porting and getting their stuff through review. Firefox for Android is also currently a nightmare to program for and progress towards feature-parity with desktop Firefox is happening a snail's pace.

/So much for my rant on the current state of affairs in add-on-land. Just in case anybody wants to know how bad things currently are…

**Comment by reallyuniquename** [comment]
Could you please share XPI file of the latest version? I don't care if it's signed ot not.

**Comment by publicarray** [comment]
@reallyuniquename I have made a singed version for myself (so that nightly stops complaining) with some changes. I'm willing to share it but be mindful that It's not 100% the code provided here.
key differences:
 - It does not contain code to migrate preferences from the old version.
 - I added a checkbox that allows the user to block same origin referrers as well. (I did not send a PR because this feature is was just for testing/advanced users and would break many sites i.e. not "smart") 
 - won't auto-update because of the different ID
 - I suppose you also have to trust that I have not modified the extension for evil.

https://seby.io/smart_referer.xpi  19c592849b141132a747c5b3ec0941a7d1755abd

**Comment by reallyuniquename** [comment]
@publicarray All right, thanks.

Few slightly unrelated questions.

Does this extension/version spoof `document.referrer` DOM property?

Can it be configured to spoof referer on direct page visit when browser sends no referer at all (e.g. bypassing hotlinking and 403s)?

**Comment by publicarray** [comment]
> Does this extension/version spoof document.referrer DOM property?

Yes, you can test it here https://seby.io/ref/ turn the Same Origin option on/off

> Can it be configured to spoof referer on direct page visit when browser sends no referer at all (e.g. bypassing hotlinking and 403s)? See #10.

I think I just found a bug where the mode can not be changed 🙊. Normally setting the mode to "Send the URL you're going to as referer" should do what you want I think.

**Comment by alexander255** [comment]
Weird… where did my response go?

Anyway I tried to implement `document.referrer` support today and it took me a lot of time to figure out that rewriting the header apparently does change the value of that variable correctly as well (we never actually interact with the page content in our code, so this *is* a surprising finding that is likely very browser specific…). I'm also fairly certain that I had known this already some long time ago… :slightly_frowning_face: 

On the bright side: We got translation support and several other small fixes out of this (#54), so it at least was worth something :smile:. (Also the current behaviour strikes make as quite a bit less than stable so the [written code](https://github.com/meh/smart-referer/tree/content-script-experiment) may still come in handy one day.)

**Comment by Gitoffthelawn** [comment]
What's the current queue position?

**Comment by meh** [comment]
Queue Position: 40 of 195

**Comment by Gitoffthelawn** [comment]
Thanks @meh 

It's interesting how long they are taking.

But at their current rate, we should expect an official release within 2 weeks.

**Comment by publicarray** [comment]
Any day now? :pray:  or has the Queue Position to negative one (-1) :stuck_out_tongue_closed_eyes:

**Comment by meh** [comment]
Queue Position: 23 of 109

**Comment by publicarray** [comment]
Thanks @meh 

It's so close I can almost taste it.

**Comment by publicarray** [comment]
@meh since we have been waiting for so long it is possible to ask at https://discourse.mozilla-community.org/c/add-ons/addons-mozilla-org if someone can look into it. This [comment](https://discourse.mozilla-community.org/t/thought-id-ask/15846/2) is also interesting.

**Comment by meh** [comment]
It's been approved.

**Comment by Gitoffthelawn** [comment]
Finally!  But why is AMO not listing it as a webextension?

**Comment by alexander255** [comment]
Because it is an embedded WebExtension with an non-sandboxed migration agent. We'll have to upload an update by the beginning of September that drops the migration agent, then it will receive the 57+ badge. You can already build a pure-WebExtension version of the extension by running `web-ext build` in the `webextension` sub-directory; the migration agent is a purely optional component already. :slightly_smiling_face:

**Comment by Gitoffthelawn** [comment]
Thanks @alexander255

**Comment by publicarray** [comment]
[Smart Referer](https://addons.mozilla.org/en-US/firefox/addon/smart-referer/) is now a hybrid extension (to migrate preferences). The code for the pure web extension is already on GitHub and is planned to ship in the [beginning of September](https://github.com/meh/smart-referer/pull/48#issuecomment-313885047)

**Comment by Gitoffthelawn** [comment]
Is it time to drop the migration agent?

**Comment by alexander255** [comment]
@Gitoffthelawn Yes.

@meh Will you look into doing #55 in the next couple of days, or should we do another intrim release?

**Pull request merged**
