### PR TITLE
Make text legible by using a standard font-size

### PR DESCRIPTION
**Pull request by Gitoffthelawn**
Text was illegible on some devices.

### CODE REVIEW

**Comment by alexander255** [comment]
Could you post a screenshot of where this is broken? Desktop or mobile? It's done this way to imitate the way the built-in part of the settings look like on desktop.

**Comment by Gitoffthelawn** [comment]
@alexander255 On the desktop.  In the example below, you can't make out the regex:

(Try clicking on the screenshot, and, at least for me, the asterisks * look like carets ^

screenshot

**Comment by alexander255** [comment]
I see… That's not how it looks for me, but apperently some fonts look crappy / are unreadable at that size.

Could you change the `font-size: x-small` to `font-size: 90.9%;` instead? (That'd be the same size as the descriptions below the labels on the left.)

Thanks!

**Comment by alexander255** [comment]
I made the change I suggested. If there are still issues with the `font-size` please create a new PR. Thanks for reporting this!

**Pull request closed without merging**
