### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by alexander255**
Translation support and some useful fixes

### CODE REVIEW

**Comment by meh** [comment]
Any other planned changes for this now that **FINALLY** they approved 0.2?

**Comment by alexander255** [comment]
I've updated this branch to add full compatibility for FireFox for Android 56+ and basic support for FireFox for Android 55.0.2+ (see #60), so please set the following minimal version requirements when uploading this version:

  * Firefox 52 or later
  * Firefox for Android 55.0.2 or later

**Comment by alexander255** [comment]
Anyway, please release this version as-is and we'll sort out the #55 related stuff later. (If you want me to do version releasing of stuff you can also add [me on AMO](https://addons.mozilla.org/de/firefox/user/alexander255_1000001/) as maintainer to the *Smart Referer* extension.)

**Comment by meh** [comment]
Pushed to AMO, awaiting review.

**Comment by meh** [comment]
It's been approved.

**Comment by alexander255** [comment]
Thanks, I'll prepare another PR now that will make use WebExtension only, not sure yet when it's the best time to merge that through… We should probably do the switch soon through.

Will you look into #55 or should I assume that issue to be dormant right now?

**Comment by meh** [comment]
Yeah I don't know either, probably mid October?

About #55 I have it open in a tab, I just need to do it.

**Pull request merged**
